### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by ghost** [Snugglez/Secondary-Auth-Skip#1]
ERROR tera-proxy-game: [dispatch] hook: unrecognized hook target S_REQUEST_SECOND_PASSWORD_AUTH<1>
    at new aks (Proxy\node_modules\Secondary-Auth-Skip\index.js:10:10)
    at Dispatch.load (Proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:195:25)
    at Dispatch.connection.dispatch.on (Proxy\lib\proxy.js:202:27)
    at Dispatch.emit (events.js:182:13)
ERROR tera-proxy-game: [dispatch] hook: unrecognized hook target C_SECOND_PASSWORD_AUTH<1>
    at new aks (Proxy\node_modules\Secondary-Auth-Skip\index.js:16:10)
    at Dispatch.load (Proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:195:25)
    at Dispatch.connection.dispatch.on (Proxy\lib\proxy.js:202:27)
    at Dispatch.emit (events.js:182:13)

**Comment by Snugglez** [comment]
The opcodes for it most likely arnt mapped, I had caali add them but not sure if they we're pushed uet

**Comment by Snugglez** [comment]
https://github.com/hackerman-caali/tera-data has them mapped

**Comment by ghost** [comment]
It works well.

**Comment by Snugglez** [comment]
Glad to know it's working
